function output=Bruggemann2021_NoHighestAbility(tau_TMTR_vec,Params,n_d,n_a,n_eta,n_theta,d_grid,a_grid,age_grid,eta_grid,theta_grid,pi_age,pi_eta,pi_theta,eta_statdist,theta_statdist,T,ReturnFn,FnsToEvaluate,DiscountFactorParamNames,vfoptions,simoptions,heteroagentoptions,transpathoptions,vfoptionstpath)

% No Highest Ability: eliminate largest eta value (highest labor productivity of worker)
n_eta=n_eta-1;
eta_grid=eta_grid(1:end-1);
pi_eta=pi_eta(1:end-1,1:end-1);
pi_eta=pi_eta./sum(pi_eta,2); % renormalize rows to one
eta_statdist=eta_statdist(1:end-1);
eta_statdist=eta_statdist/sum(eta_statdist); % renormalize mass to one

%% Now recreate n_z, z_grid and pi_z without highest ability
% These lines are all just copy-paste, as we have changed n_eta, eta_grid, pi_eta, and eta_statdist
n_z=[n_eta*n_theta+1,1,1]; % joint-grid, n_eta*n_theta points for young, 1 point for old
% For z_grid, first 20 rows are young, last row is old
z_grid=[age_grid(1)*ones(n_eta*n_theta,1), repmat(eta_grid,n_theta,1), repelem(theta_grid,n_eta,1); age_grid(2),0,0]; % note: use zero for eta and theta when old, so you will get issues if you try to do anything with them


pi_etatheta=kron(pi_theta, pi_eta); % in reverse order [young-young]

etatheta_statdist=kron(theta_statdist,eta_statdist); % in reverse order
pi_newborn=etatheta_statdist'; % i.i.d. based on etatheta_statdist

pi_z=[pi_age(1,1)*pi_etatheta, pi_age(1,2)*ones(n_eta*n_theta,1);...  % top left is young-young, top right is young-old, 
    pi_age(2,1)*pi_newborn, pi_age(2,2)]; % bottom left is old-young, bottom right is old-old

% Convert the statutory rates to those used by the model
tau_i_r6_vec=Params.tau_i_adj*tau_TMTR_vec;


%%
% GEPriceParamNames is set per stage in the Initial Stationary Eqm section below: the
% benchmark solves {r,w,tau_s,G,pension,ybar} then {r,w,tau_s}, and the tax experiments
% then use {r,w,lumpsum}. (w need not really be a GE price, since the Cobb-Douglas corporate
% sector pins a relation between w and r in a stationary eqm -- though not on a transition.)

GeneralEqmEqns.CapitalMarket = @(r,K_corp,N_corp,alpha,delta,Z) r-(alpha*Z*(K_corp^(alpha-1))*(N_corp^(1-alpha))-delta); %The requirement that the interest rate corresponds to the marginal product of capital in corporate sector
GeneralEqmEqns.LaborMarket = @(w,K_corp,N_corp,alpha,Z) w-(1-alpha)*Z*(K_corp^(alpha))*(N_corp^(-alpha)); %The requirement that the interest rate corresponds to the marginal product of capital in corporate sector
GeneralEqmEqns.GovBudget = @(G,PensionSpending,IncomeTaxRevenue,ConsumptionTaxRevenue,lumpsum) G+PensionSpending+lumpsum-IncomeTaxRevenue-ConsumptionTaxRevenue; %Government runs balanced budget [take advantage of the fact that lumpsum is same for all, so adding up across everyone just gives the lumpsum parameter value; note, lumpsum=0 in baseline]
% B2021, pg 16-17: "When increasing the effective TMTR, I keep the level of government spending (including transfers to retirees) as
% well as other tax parameters such as the tax brackets and standard deductions at their benchmark level. Any additional tax revenue
% generated by the tax increase is redistributed through a tax-free lump-sum transfer to all households.

FnsToEvaluate_TransPath.K_noncorp=FnsToEvaluate.K_noncorp;
FnsToEvaluate_TransPath.A=FnsToEvaluate.A;
FnsToEvaluate_TransPath.N_noncorp=FnsToEvaluate.N_noncorp;
FnsToEvaluate_TransPath.N_lbar=FnsToEvaluate.N_lbar;
FnsToEvaluate_TransPath.L=FnsToEvaluate.L;
FnsToEvaluate_TransPath.IncomeTaxRevenue=FnsToEvaluate.IncomeTaxRevenue;
FnsToEvaluate_TransPath.ConsumptionTaxRevenue=FnsToEvaluate.ConsumptionTaxRevenue;
FnsToEvaluate_TransPath.PensionSpending=FnsToEvaluate.PensionSpending;

TransPathGeneralEqmEqns.CapitalMarket = @(r,K_noncorp,A,N_noncorp,N_lbar,L,alpha,delta,Z) r-(alpha*Z*((A-K_noncorp)^(alpha-1))*((L-N_lbar-N_noncorp)^(1-alpha))-delta); %The requirement that the interest rate corresponds to the marginal product of capital in corporate sector
TransPathGeneralEqmEqns.LaborMarket = @(w,K_noncorp,A,N_noncorp,N_lbar,L,alpha,Z) w-(1-alpha)*Z*((A-K_noncorp)^(alpha))*((L-N_lbar-N_noncorp)^(-alpha)); %The requirement that the interest rate corresponds to the marginal product of capital in corporate sector
TransPathGeneralEqmEqns.GovBudget = @(G,PensionSpending,IncomeTaxRevenue,ConsumptionTaxRevenue,lumpsum) G+PensionSpending+lumpsum-IncomeTaxRevenue-ConsumptionTaxRevenue;  %Government runs balanced budget
% Note: For this model the transition path has the same general equilibrium conditions as the stationary equilibrium, but this will not always be true for more complex models.

transpathoptions.GEnewprice=2; % 2=Anderson acceleration of the shooting map (3=plain shooting)
% Need to explain to transpathoptions how to use the GeneralEqmEqns to
% update the general eqm transition prices (in PricePath).
transpathoptions.GEnewprice2.howtoupdate=... % a row is: GEcondn, price, add, factor
    {'CapitalMarket','r',0,0.1;... % CapitalMarket is postivie is r is to large, so subtract
    'LaborMarket','w',0,0.1;... % LaborMarket is postivie is r is to large, so subtract
    'GovBudget','lumpsum',0,0.1}; % GovBudget is positive if lumpsum is too big, so subtract
% Note: the update is essentially new_price=price+factor*add*GEcondn_value-factor*(1-add)*GEcondn_value
% Notice that this adds factor*GEcondn_value when add=1 and subtracts it what add=0
% A small 'factor' will make the convergence to solution take longer, but too large a value will make it
% unstable (fail to converge). Technically this is the damping factor in a shooting algorithm.
% 2026-09-23: the GovBudget factor here was 0.01, ten times the driver's damping. Measured
% tail contraction was 0.990 per iteration in both Part 5 economies, i.e. exactly 1-factor,
% so Anderson accelerated for ~10 iterations and then handed the tail back to a crippled
% map: 170-200+ iterations per transition against the driver's 9-13 at factor 0.1.
% Raising Anderson memory to 10 changed nothing, confirming the map and not the
% accelerator was the bottleneck. Watch the first transition: if 0.1 is unstable here the
% distance will climb rather than fall, within the first few iterations.

% Now just run the TransitionPath_InfHorz command (all of the other inputs
% are things we had already had to define to be able to solve for the initial and final equilibria)
transpathoptions.weightscheme=1;
transpathoptions.verbose=1;

% The four 'results' that will be output
CEV_StationaryEqm=zeros(length(tau_i_r6_vec),1);
CEV_TPath=zeros(length(tau_i_r6_vec),1);
LafferCurve_LumpSumTPathPeriod1=zeros(length(tau_i_r6_vec),1);
LafferCurve_LumpSum=zeros(length(tau_i_r6_vec),1);

%% Initial Stationary Eqm
% This counterfactual economy gets its OWN benchmark equilibrium, which is what B2021 does:
% her benchmark.f90 is byte-identical across baseline/no_entrepreneurs/no_highest_labor_abil
% and is re-run for each, the counterfactual entering only through parameters.txt (the theta
% and eta transition probabilities; yadj stays at its baseline calibration in all three).
% In that program G and the pension are RATIOS, not levels:
%    line 1551:  transf = replrate*totinc          pension = 0.4 x total income
%    line 2128:  ... - gfrac*gdp - transf*totret   G       = 0.146 x gdp
% so both float with the economy and the income tax balances the budget (its update_tax
% loop). Our Params.pensionreplacementrate=0.4 and Params.GdivYtarget=0.146 are exactly her
% replrate and gfrac. Inheriting the baseline LEVELS instead forced a lump-sum TAX of about
% 13 percent of average income here, just to fund a G the smaller tax base cannot support,
% which contaminated every welfare comparison built on this economy.
Params.lumpsum=0; % no lump-sum transfer in a benchmark; the income tax clears the budget
GEPriceParamNames={'r','w','tau_s','G','pension','ybar'};
GeneralEqmEqns.Pensions = @(pension,ybar,pensionreplacementrate) pension/ybar - pensionreplacementrate; % her replrate
GeneralEqmEqns.AvgIncome = @(ybar,Income) ybar - Income; % her totinc
GeneralEqmEqns.SizeOfGovernment = @(G,Y,GdivYtarget) G/Y-GdivYtarget; % her gfrac
heteroagentoptions.constrainpositive={'r','w','tau_s','pension','ybar'};
[p_eqm_initial0,~]=HeteroAgentStationaryEqm_InfHorz(n_d, n_a, n_z, 0, pi_z, d_grid, a_grid, z_grid, ReturnFn, FnsToEvaluate, GeneralEqmEqns, Params, DiscountFactorParamNames, [], [], [], GEPriceParamNames,heteroagentoptions, simoptions, vfoptions);

Params.r=p_eqm_initial0.r;
Params.w=p_eqm_initial0.w;
Params.tau_s=p_eqm_initial0.tau_s;
Params.G=p_eqm_initial0.G;
Params.pension=p_eqm_initial0.pension;
Params.ybar=p_eqm_initial0.ybar;

% Re-solve without the calibration targets, to get a clean general eqm (as the driver's Part 1 does)
GEPriceParamNames={'r','w','tau_s'};
heteroagentoptions.constrainpositive={'w'};
GeneralEqmEqns=rmfield(GeneralEqmEqns,'SizeOfGovernment');
GeneralEqmEqns=rmfield(GeneralEqmEqns,'Pensions');
GeneralEqmEqns=rmfield(GeneralEqmEqns,'AvgIncome');
[p_eqm_initial,GeneralEqmCondn_initial]=HeteroAgentStationaryEqm_InfHorz(n_d, n_a, n_z, 0, pi_z, d_grid, a_grid, z_grid, ReturnFn, FnsToEvaluate, GeneralEqmEqns, Params, DiscountFactorParamNames, [], [], [], GEPriceParamNames,heteroagentoptions, simoptions, vfoptions);

Params.r=p_eqm_initial.r; % Put the equilibrium interest rate into Params so we can use it to calculate things based on equilibrium parameters
Params.w=p_eqm_initial.w;
Params.tau_s=p_eqm_initial.tau_s;

% The tax experiments below then hold THIS economy's G, pension and ybar at its own benchmark
% and let the lump-sum transfer absorb the extra revenue, per B2021 pg 16-17.
GEPriceParamNames={'r','w','lumpsum'};

[V_initial,Policy_initial]=ValueFnIter_InfHorz(n_d,n_a,n_z,d_grid,a_grid,z_grid, pi_z, ReturnFn, Params, DiscountFactorParamNames, [], vfoptions);
StationaryDist_initial=StationaryDist_InfHorz(Policy_initial,n_d,n_a,n_z,pi_z, simoptions);

% For the CEV welfare evaluations later, we need
BehindTheVeil_V_Initial=sum(sum(sum(V_initial(:,1,:,:).*StationaryDist_initial(:,1,:,:))));
% And we need to calculate the lifetime utility of consumption (the value fn omitting the utility of leisure).
% Easiest it just to set parameter chi to zero, so there is no utility of leisure
xi_backup=Params.xi;
Params.xi=0; % no utility of leisure, so consumption is the only source of utility
V_ConsOnly_initial=ValueFnFromPolicy_InfHorz(Policy_initial,n_d,n_a,n_z,d_grid,a_grid,z_grid,pi_z,ReturnFn,Params,DiscountFactorParamNames,vfoptions);
% Put chi back into Params
Params.xi=xi_backup;
BehindTheVeil_V_ConsOnly_Initial=sum(sum(sum(V_ConsOnly_initial(:,1,:,:).*StationaryDist_initial(:,1,:,:))));

doublecheck.GeneralEqmCondn_initial=GeneralEqmCondn_initial;

%% Loop over TMTR
for ii=1:length(tau_i_r6_vec)
    ii
    Params.tau_i_r6=tau_i_r6_vec(ii);
    % Params.r=p_eqm_initial.r; % use benchmark economy as initial guess
    % Params.w=p_eqm_initial.w; % use benchmark economy as initial guess
    % Params.lumpsum=0; % use benchmark economy as initial guess

    %% Final Stationary Eqm
    [p_eqm_final,GeneralEqmCondn_final]=HeteroAgentStationaryEqm_InfHorz(n_d, n_a, n_z, 0, pi_z, d_grid, a_grid, z_grid, ReturnFn, FnsToEvaluate, GeneralEqmEqns, Params, DiscountFactorParamNames, [], [], [], GEPriceParamNames,heteroagentoptions, simoptions, vfoptions);

    Params.r=p_eqm_final.r; % Put the equilibrium interest rate into Params so we can use it to calculate things based on equilibrium parameters
    Params.w=p_eqm_final.w;
    Params.lumpsum=p_eqm_final.lumpsum;

    [V_final,Policy_final]=ValueFnIter_InfHorz(n_d,n_a,n_z,d_grid,a_grid,z_grid, pi_z, ReturnFn, Params, DiscountFactorParamNames, [], vfoptions);
    StationaryDist_final=StationaryDist_InfHorz(Policy_final,n_d,n_a,n_z,pi_z, simoptions);
    
    % Consumption Equivalent Variation (welfare gain/loss)
    % We just calculate the 'behind-the-veil' expected lifetime utility
    % in the baseline and each final eqm.
    BehindTheVeil_V_final=sum(sum(sum(V_final(:,1,:,:).*StationaryDist_final(:,1,:,:))));
    % B2021 ignores leisure keeping it constant, and this together with the fact
    % that utility is separable and the utility of consumption is a CES utility fn,
    % we get that CEV is given by the following simple formula
    WelfareChange=BehindTheVeil_V_final-BehindTheVeil_V_Initial;
    CEV=(WelfareChange/BehindTheVeil_V_ConsOnly_Initial+1)^(1/(1-Params.sigma1)) -1;
    % Key to this formula being so simple is the strong assumption to
    % just ignore leisure; together with separable utility and a CES
    % utility of consumption.
    %
    % Note: B2021 defines CEV in eqn (19) on page
    % Shows how to derive this simplified formula in Appendix C, on pg 32.

    CEV_StationaryEqm(ii)=CEV;

    %% Transition path
    % We want to look at a one off unanticipated path of tau_i_r6 (the top marginal tax rate).
    ParamPath.tau_i_r6=Params.tau_i_r6*ones(T,1); % ParamPath is matrix of size T-by-'number of parameters that change over path'
    % (the way ParamPath is set is designed to allow for a series of changes in the parameters)

    % We need to give an initial guess for the price path
    PricePath0.r=[linspace(p_eqm_initial.r, p_eqm_final.r, floor(T/3))'; p_eqm_final.r*ones(T-floor(T/3),1)]; % For each price/parameter that will be determined in general eqm over transition path PricePath0 is matrix of size T-by-1
    PricePath0.w=[linspace(p_eqm_initial.w, p_eqm_final.w, floor(T/3))'; p_eqm_final.w*ones(T-floor(T/3),1)];
    PricePath0.lumpsum=[linspace(0, p_eqm_final.lumpsum, floor(T/3))'; p_eqm_final.lumpsum*ones(T-floor(T/3),1)];

    transpathoptions.maxiter=200;
    [PricePath,GeneralEqmCondnPath]=TransitionPath_InfHorz(PricePath0, ParamPath, T, V_final, StationaryDist_initial, n_d, n_a, n_z, d_grid,a_grid,z_grid, pi_z, ReturnFn, FnsToEvaluate_TransPath, TransPathGeneralEqmEqns, Params, DiscountFactorParamNames, transpathoptions, simoptions,vfoptionstpath);

    [VPath,PolicyPath]=ValueFnOnTransPath_InfHorz(PricePath, ParamPath, T, V_final, Policy_final, Params, n_d, n_a, n_z, d_grid, a_grid,z_grid, pi_z, DiscountFactorParamNames, ReturnFn, transpathoptions, vfoptionstpath);
    % AgentDistPath=AgentDistOnTransPath_InfHorz(StationaryDist_initial, PolicyPath,n_d,n_a,n_z,pi_z,T,simoptions);
    % AggVarsPath=EvalFnOnTransPath_AggVars_InfHorz(FnsToEvaluate_TransPath,AgentDistPath,PolicyPath,PricePath,ParamPath, Params, T, n_d, n_a, n_z, d_grid, a_grid,z_grid,simoptions);

    % YPath=Params.Z*(AggVarsPath.A.Mean.^(Params.alpha)).*(AggVarsPath.L.Mean.^(1-Params.alpha));

    % Consumption Equivalent Variation (welfare gain/loss)
    % We just calculate the 'behind-the-veil' expected lifetime utility in the baseline and each final eqm.
    % This calculation is essentially the same as we did to compare
    % steady-states, just using first period of VPath instead of V_final.
    % See previous for explanation and details.
    BehindTheVeil_VPath=sum(sum(sum(VPath(:,1,:,:,1).*StationaryDist_initial(:,1,:,:))));
    WelfareChange=BehindTheVeil_VPath-BehindTheVeil_V_Initial;
    CEVpath=(WelfareChange/BehindTheVeil_V_ConsOnly_Initial+1)^(1/(1-Params.sigma1)) -1;

    CEV_TPath(ii)=CEVpath;
    
    % For Figure A1 we keep
    LafferCurve_LumpSumTPathPeriod1(ii)=PricePath.lumpsum(1);
    LafferCurve_LumpSum(ii)=p_eqm_final.lumpsum;

    doublecheck.GeneralEqmCondn_final(ii).GeneralEqmCondn_final=GeneralEqmCondn_final;
    doublecheck.GeneralEqmCondnPath(ii).GeneralEqmCondnPath=GeneralEqmCondnPath;

end

% Diagnostics only. Saving the whole function workspace here captured the full
% transition-path objects for all 14 tax rates; these five are what is actually wanted
% (and all five are also returned in output, so this file is a convenience copy).
save ./SavedOutput/B2021_NoHighestAbility.mat doublecheck CEV_TPath CEV_StationaryEqm ...
    LafferCurve_LumpSum LafferCurve_LumpSumTPathPeriod1


% Four things here are output
% Two are the CEV results, that form Figure 6 Panel A
output.CEV_TPath=CEV_TPath;
output.CEV_StationaryEqm=CEV_StationaryEqm;
% Two are so I can do a Laffer Curve comparison of the entrepreneur and no-entrepreneur models, just out of interest
output.LafferCurve_LumpSum=LafferCurve_LumpSum;
output.LafferCurve_LumpSumTPathPeriod1=LafferCurve_LumpSumTPathPeriod1;

output.doublecheck=doublecheck; % So I can check all the convergence worked okay






end